# docker-compose.yml
version: '3'
services:
    idengine:
        image: thisdougb/idengine:latest
        ports:
            - "8000:8000"
        environment:
            - IDENGINE_VAULT_HOST=http://vault:8201 # developer mode http
            - IDENGINE_VAULT_TOKEN=developer
        command: /app/idengine -vault # use the HashiCorp Vault datastore

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    # HashiCorp Vault in developer mode, see config/vault.json
    vault:
      image: vault:latest
      ports:
        - 8201:8201
      volumes:
          - .vault/config:/vault/config:rw
      environment:
        - VAULT_ADDR=http://127.0.0.1:8201 # developer mode http
        - VAULT_TOKEN=developer
        - VAULT_DEV_ROOT_TOKEN_ID=developer
        - VAULT_LOG_LEVEL=debug
      cap_add:
        - IPC_LOCK
      command: vault server -dev -config=/vault/config/vault.json
